### ISSUE TITLE
👩🏻‍💻 새로운 Label 소개합니다

### ISSUE THREAD

**Issue by 55555-Jyeon** [interview-crossing/fe-tech-interview#65]
#### ✨New PR

저는 브랜치를 여러 개 만들고 싶지 않아서 하나의 브랜치에 new pull request로 PR을 생성해왔습니다.
그래서 여러 개의 PR을 올려야할 경우 반드시 열린 PR을 페어가 꼬꼬무를 달아주기 전에 닫아야 하는 상황이 발생하게 됩니다.

이런 상황에서 새로 올린 PR이 이전에 닫힌 PR과 구분되게 하기 위해 만든 라벨입니다.
혹은 올린 PR의 내용이나 질문에 대한 대답이 변경된 경우에도 추가할 수 있을 것 같아요.

<br />

#### 👩🏻‍💻 질문했어요

새로운 PR을 확인한 페어가 추가 질문을 달았다면 해당 라벨을 붙여 PR 생성자(면접자)에게 빠르게 알려줄 수 있는 라벨입니다.
해당 라벨이 붙어 있는 PR 생성자(면접자)는 최대한 빠른 시일 내에 대답해주세요.

<br />

#### 🙋🏻‍♀️ 답변했어요

페어(면접관)의 질문을 확인 후 답변을 달았다면 라벨을 답변했어요로 변경해주세요!
PR 생성자(면접자)의 라벨이 답변했어요로 되어 잇다면 페어(면접관)은 추가 질문할 내용이 있는지 확인해주세요.

<br />

더 이상 추가 질문이 없다면 아래와 같은 답변을 달아주세요!
PR 생성자(면접자)는 위의 라벨이 붙어 있지 않을 경우, 페어(면접관)의 마지막 댓글을 확인하고 해당 PR을 머지해주세요.

```js
<div align="end">
<h3> $\color{#FFA832}{🎤 면접관}$ </h3>

<!-- 면접관 입장에서, 질문을 작성해주세요. -->
네, 성실히 답해주셔서 감사합니다 :)

</div>
```

혹은 단톡방에 공유 후 머지시켜도 무방합니다 :)
팀 별 룰에 맞게 진행해주세요!

<br />

**Comment by TransparentDeveloper** [comment]
역시.. 좋습니다.!
